BARANGAY_DATA = [
  { province_name: "Metro Manila", city_name: "Manila", name: "Acacia Heights" },
  { province_name: "Metro Manila", city_name: "Quezon City", name: "Acacia Village" },
  { province_name: "Metro Manila", city_name: "Caloocan", name: "Acacia Proper" },
  { province_name: "Metro Manila", city_name: "Las Pinas", name: "Acacia Central" },
  { province_name: "Metro Manila", city_name: "Makati", name: "Acacia Norte" },
  { province_name: "Metro Manila", city_name: "Malabon", name: "Acacia Sur" },
  { province_name: "Metro Manila", city_name: "Mandaluyong", name: "Acacia Silangan" },
  { province_name: "Metro Manila", city_name: "Marikina", name: "Acacia Kanluran" },
  { province_name: "Metro Manila", city_name: "Muntinlupa", name: "Acacia Riverside" },
  { province_name: "Metro Manila", city_name: "Navotas", name: "Acacia Hills" },
  { province_name: "Metro Manila", city_name: "Paranaque", name: "Amihan Heights" },
  { province_name: "Metro Manila", city_name: "Pasay", name: "Amihan Village" },
  { province_name: "Metro Manila", city_name: "Pasig", name: "Amihan Proper" },
  { province_name: "Metro Manila", city_name: "San Juan", name: "Amihan Central" },
  { province_name: "Metro Manila", city_name: "Taguig", name: "Amihan Norte" },
  { province_name: "Metro Manila", city_name: "Valenzuela", name: "Amihan Sur" },
  { province_name: "Metro Manila", city_name: "Pateros", name: "Amihan Silangan" },
  { province_name: "Abra", city_name: "Bangued", name: "Amihan Kanluran" },
  { province_name: "Apayao", city_name: "Kabugao", name: "Amihan Riverside" },
  { province_name: "Benguet", city_name: "La Trinidad", name: "Amihan Hills" },
  { province_name: "Ifugao", city_name: "Lagawe", name: "BagongBayan Heights" },
  { province_name: "Kalinga", city_name: "Tabuk", name: "BagongBayan Village" },
  { province_name: "Mountain Province", city_name: "Bontoc", name: "BagongBayan Proper" },
  { province_name: "Ilocos Norte", city_name: "Laoag", name: "BagongBayan Central" },
  { province_name: "Ilocos Norte", city_name: "Batac", name: "BagongBayan Norte" },
  { province_name: "Ilocos Sur", city_name: "Vigan", name: "BagongBayan Sur" },
  { province_name: "Ilocos Sur", city_name: "Candon", name: "BagongBayan Silangan" },
  { province_name: "La Union", city_name: "San Fernando", name: "BagongBayan Kanluran" },
  { province_name: "Pangasinan", city_name: "Lingayen", name: "BagongBayan Riverside" },
  { province_name: "Pangasinan", city_name: "Dagupan", name: "BagongBayan Hills" },
  { province_name: "Pangasinan", city_name: "Urdaneta", name: "Bayani Heights" },
  { province_name: "Batanes", city_name: "Basco", name: "Bayani Village" },
  { province_name: "Cagayan", city_name: "Tuguegarao", name: "Bayani Proper" },
  { province_name: "Cagayan", city_name: "Aparri", name: "Bayani Central" },
  { province_name: "Isabela", city_name: "Ilagan", name: "Bayani Norte" },
  { province_name: "Isabela", city_name: "Cauayan", name: "Bayani Sur" },
  { province_name: "Nueva Vizcaya", city_name: "Bayombong", name: "Bayani Silangan" },
  { province_name: "Nueva Vizcaya", city_name: "Solano", name: "Bayani Kanluran" },
  { province_name: "Quirino", city_name: "Cabarroguis", name: "Bayani Riverside" },
  { province_name: "Aurora", city_name: "Baler", name: "Bayani Hills" },
  { province_name: "Bataan", city_name: "Balanga", name: "Bukal Heights" },
  { province_name: "Bulacan", city_name: "Malolos", name: "Bukal Village" },
  { province_name: "Bulacan", city_name: "Meycauayan", name: "Bukal Proper" },
  { province_name: "Bulacan", city_name: "San Jose del Monte", name: "Bukal Central" },
  { province_name: "Nueva Ecija", city_name: "Palayan", name: "Bukal Norte" },
  { province_name: "Nueva Ecija", city_name: "Cabanatuan", name: "Bukal Sur" },
  { province_name: "Nueva Ecija", city_name: "Gapan", name: "Bukal Silangan" },
  { province_name: "Pampanga", city_name: "San Fernando", name: "Bukal Kanluran" },
  { province_name: "Pampanga", city_name: "Angeles", name: "Bukal Riverside" },
  { province_name: "Pampanga", city_name: "Mabalacat", name: "Bukal Hills" },
  { province_name: "Tarlac", city_name: "Tarlac City", name: "Dakila Heights" },
  { province_name: "Zambales", city_name: "Iba", name: "Dakila Village" },
  { province_name: "Zambales", city_name: "Olongapo", name: "Dakila Proper" },
  { province_name: "Batangas", city_name: "Batangas City", name: "Dakila Central" },
  { province_name: "Batangas", city_name: "Lipa", name: "Dakila Norte" },
  { province_name: "Batangas", city_name: "Tanauan", name: "Dakila Sur" },
  { province_name: "Cavite", city_name: "Trece Martires", name: "Dakila Silangan" },
  { province_name: "Cavite", city_name: "Imus", name: "Dakila Kanluran" },
  { province_name: "Cavite", city_name: "Dasmarinas", name: "Dakila Riverside" },
  { province_name: "Cavite", city_name: "Tagaytay", name: "Dakila Hills" },
  { province_name: "Laguna", city_name: "Santa Cruz", name: "Dalisay Heights" },
  { province_name: "Laguna", city_name: "Calamba", name: "Dalisay Village" },
  { province_name: "Laguna", city_name: "San Pablo", name: "Dalisay Proper" },
  { province_name: "Laguna", city_name: "Santa Rosa", name: "Dalisay Central" },
  { province_name: "Laguna", city_name: "Binan", name: "Dalisay Norte" },
  { province_name: "Quezon", city_name: "Lucena", name: "Dalisay Sur" },
  { province_name: "Quezon", city_name: "Tayabas", name: "Dalisay Silangan" },
  { province_name: "Rizal", city_name: "Antipolo", name: "Dalisay Kanluran" },
  { province_name: "Marinduque", city_name: "Boac", name: "Dalisay Riverside" },
  { province_name: "Occidental Mindoro", city_name: "Mamburao", name: "Dalisay Hills" },
  { province_name: "Occidental Mindoro", city_name: "San Jose", name: "Diwa Heights" },
  { province_name: "Oriental Mindoro", city_name: "Calapan", name: "Diwa Village" },
  { province_name: "Palawan", city_name: "Puerto Princesa", name: "Diwa Proper" },
  { province_name: "Palawan", city_name: "Coron", name: "Diwa Central" },
  { province_name: "Romblon", city_name: "Romblon", name: "Diwa Norte" },
  { province_name: "Albay", city_name: "Legazpi", name: "Diwa Sur" },
  { province_name: "Albay", city_name: "Ligao", name: "Diwa Silangan" },
  { province_name: "Albay", city_name: "Tabaco", name: "Diwa Kanluran" },
  { province_name: "Camarines Norte", city_name: "Daet", name: "Diwa Riverside" },
  { province_name: "Camarines Sur", city_name: "Pili", name: "Diwa Hills" },
  { province_name: "Camarines Sur", city_name: "Naga", name: "Gintong Heights" },
  { province_name: "Camarines Sur", city_name: "Iriga", name: "Gintong Village" },
  { province_name: "Catanduanes", city_name: "Virac", name: "Gintong Proper" },
  { province_name: "Masbate", city_name: "Masbate City", name: "Gintong Central" },
  { province_name: "Sorsogon", city_name: "Sorsogon City", name: "Gintong Norte" },
  { province_name: "Aklan", city_name: "Kalibo", name: "Gintong Sur" },
  { province_name: "Antique", city_name: "San Jose de Buenavista", name: "Gintong Silangan" },
  { province_name: "Capiz", city_name: "Roxas City", name: "Gintong Kanluran" },
  { province_name: "Guimaras", city_name: "Jordan", name: "Gintong Riverside" },
  { province_name: "Iloilo", city_name: "Iloilo City", name: "Gintong Hills" },
  { province_name: "Iloilo", city_name: "Passi", name: "Gulod Heights" },
  { province_name: "Negros Occidental", city_name: "Bacolod", name: "Gulod Village" },
  { province_name: "Negros Occidental", city_name: "Bago", name: "Gulod Proper" },
  { province_name: "Negros Occidental", city_name: "Kabankalan", name: "Gulod Central" },
  { province_name: "Negros Occidental", city_name: "San Carlos", name: "Gulod Norte" },
  { province_name: "Bohol", city_name: "Tagbilaran", name: "Gulod Sur" },
  { province_name: "Bohol", city_name: "Talibon", name: "Gulod Silangan" },
  { province_name: "Cebu", city_name: "Cebu City", name: "Gulod Kanluran" },
  { province_name: "Cebu", city_name: "Danao", name: "Gulod Riverside" },
  { province_name: "Cebu", city_name: "Toledo", name: "Gulod Hills" },
  { province_name: "Cebu", city_name: "Talisay", name: "Halcon Heights" },
  { province_name: "Cebu", city_name: "Bogo", name: "Halcon Village" },
  { province_name: "Cebu", city_name: "Carcar", name: "Halcon Proper" },
  { province_name: "Cebu", city_name: "Naga", name: "Halcon Central" },
  { province_name: "Negros Oriental", city_name: "Dumaguete", name: "Halcon Norte" },
  { province_name: "Negros Oriental", city_name: "Bais", name: "Halcon Sur" },
  { province_name: "Negros Oriental", city_name: "Bayawan", name: "Halcon Silangan" },
  { province_name: "Negros Oriental", city_name: "Tanjay", name: "Halcon Kanluran" },
  { province_name: "Negros Oriental", city_name: "Canlaon", name: "Halcon Riverside" },
  { province_name: "Negros Oriental", city_name: "Guihulngan", name: "Halcon Hills" },
  { province_name: "Siquijor", city_name: "Siquijor", name: "IlangIlang Heights" },
  { province_name: "Biliran", city_name: "Naval", name: "IlangIlang Village" },
  { province_name: "Eastern Samar", city_name: "Borongan", name: "IlangIlang Proper" },
  { province_name: "Leyte", city_name: "Tacloban", name: "IlangIlang Central" },
  { province_name: "Leyte", city_name: "Ormoc", name: "IlangIlang Norte" },
  { province_name: "Leyte", city_name: "Baybay", name: "IlangIlang Sur" },
  { province_name: "Northern Samar", city_name: "Catarman", name: "IlangIlang Silangan" },
  { province_name: "Samar", city_name: "Catbalogan", name: "IlangIlang Kanluran" },
  { province_name: "Samar", city_name: "Calbayog", name: "IlangIlang Riverside" },
  { province_name: "Southern Leyte", city_name: "Maasin", name: "IlangIlang Hills" },
  { province_name: "Zamboanga del Norte", city_name: "Dipolog", name: "Kaunlaran Heights" },
  { province_name: "Zamboanga del Norte", city_name: "Dapitan", name: "Kaunlaran Village" },
  { province_name: "Zamboanga del Sur", city_name: "Pagadian", name: "Kaunlaran Proper" },
  { province_name: "Zamboanga del Sur", city_name: "Zamboanga City", name: "Kaunlaran Central" },
  { province_name: "Zamboanga Sibugay", city_name: "Ipil", name: "Kaunlaran Norte" },
  { province_name: "Bukidnon", city_name: "Malaybalay", name: "Kaunlaran Sur" },
  { province_name: "Bukidnon", city_name: "Valencia", name: "Kaunlaran Silangan" },
  { province_name: "Camiguin", city_name: "Mambajao", name: "Kaunlaran Kanluran" },
  { province_name: "Lanao del Norte", city_name: "Tubod", name: "Kaunlaran Riverside" },
  { province_name: "Lanao del Norte", city_name: "Iligan", name: "Kaunlaran Hills" },
  { province_name: "Misamis Occidental", city_name: "Oroquieta", name: "Luntian Heights" },
  { province_name: "Misamis Occidental", city_name: "Ozamiz", name: "Luntian Village" },
  { province_name: "Misamis Occidental", city_name: "Tangub", name: "Luntian Proper" },
  { province_name: "Misamis Oriental", city_name: "Cagayan de Oro", name: "Luntian Central" },
  { province_name: "Misamis Oriental", city_name: "Gingoog", name: "Luntian Norte" },
  { province_name: "Misamis Oriental", city_name: "El Salvador", name: "Luntian Sur" },
  { province_name: "Davao de Oro", city_name: "Nabunturan", name: "Luntian Silangan" },
  { province_name: "Davao del Norte", city_name: "Tagum", name: "Luntian Kanluran" },
  { province_name: "Davao del Norte", city_name: "Panabo", name: "Luntian Riverside" },
  { province_name: "Davao del Norte", city_name: "Samal", name: "Luntian Hills" },
  { province_name: "Davao del Sur", city_name: "Digos", name: "Maharlika Heights" },
  { province_name: "Davao del Sur", city_name: "Davao City", name: "Maharlika Village" },
  { province_name: "Davao Occidental", city_name: "Malita", name: "Maharlika Proper" },
  { province_name: "Davao Oriental", city_name: "Mati", name: "Maharlika Central" },
  { province_name: "Cotabato", city_name: "Kidapawan", name: "Maharlika Norte" },
  { province_name: "Sarangani", city_name: "Alabel", name: "Maharlika Sur" },
  { province_name: "South Cotabato", city_name: "Koronadal", name: "Maharlika Silangan" },
  { province_name: "South Cotabato", city_name: "General Santos", name: "Maharlika Kanluran" },
  { province_name: "Sultan Kudarat", city_name: "Isulan", name: "Maharlika Riverside" },
  { province_name: "Sultan Kudarat", city_name: "Tacurong", name: "Maharlika Hills" },
  { province_name: "Agusan del Norte", city_name: "Butuan", name: "Malaya Heights" },
  { province_name: "Agusan del Norte", city_name: "Cabadbaran", name: "Malaya Village" },
  { province_name: "Agusan del Sur", city_name: "Prosperidad", name: "Malaya Proper" },
  { province_name: "Agusan del Sur", city_name: "Bayugan", name: "Malaya Central" },
  { province_name: "Dinagat Islands", city_name: "San Jose", name: "Malaya Norte" },
  { province_name: "Surigao del Norte", city_name: "Surigao City", name: "Malaya Sur" },
  { province_name: "Surigao del Sur", city_name: "Tandag", name: "Malaya Silangan" },
  { province_name: "Surigao del Sur", city_name: "Bislig", name: "Malaya Kanluran" },
  { province_name: "Basilan", city_name: "Isabela City", name: "Malaya Riverside" },
  { province_name: "Lanao del Sur", city_name: "Marawi", name: "Malaya Hills" },
  { province_name: "Maguindanao del Norte", city_name: "Datu Odin Sinsuat", name: "Mapayapa Heights" },
  { province_name: "Maguindanao del Norte", city_name: "Cotabato City", name: "Mapayapa Village" },
  { province_name: "Maguindanao del Sur", city_name: "Buluan", name: "Mapayapa Proper" },
  { province_name: "Sulu", city_name: "Jolo", name: "Mapayapa Central" },
  { province_name: "Tawi-Tawi", city_name: "Bongao", name: "Mapayapa Norte" },
  { province_name: "Metro Manila", city_name: "Manila", name: "Mapayapa Sur" },
  { province_name: "Metro Manila", city_name: "Quezon City", name: "Mapayapa Silangan" },
  { province_name: "Metro Manila", city_name: "Caloocan", name: "Mapayapa Kanluran" },
  { province_name: "Metro Manila", city_name: "Las Pinas", name: "Mapayapa Riverside" },
  { province_name: "Metro Manila", city_name: "Makati", name: "Mapayapa Hills" },
  { province_name: "Metro Manila", city_name: "Malabon", name: "Masigla Heights" },
  { province_name: "Metro Manila", city_name: "Mandaluyong", name: "Masigla Village" },
  { province_name: "Metro Manila", city_name: "Marikina", name: "Masigla Proper" },
  { province_name: "Metro Manila", city_name: "Muntinlupa", name: "Masigla Central" },
  { province_name: "Metro Manila", city_name: "Navotas", name: "Masigla Norte" },
  { province_name: "Metro Manila", city_name: "Paranaque", name: "Masigla Sur" },
  { province_name: "Metro Manila", city_name: "Pasay", name: "Masigla Silangan" },
  { province_name: "Metro Manila", city_name: "Pasig", name: "Masigla Kanluran" },
  { province_name: "Metro Manila", city_name: "San Juan", name: "Masigla Riverside" },
  { province_name: "Metro Manila", city_name: "Taguig", name: "Masigla Hills" },
  { province_name: "Metro Manila", city_name: "Valenzuela", name: "Pagasa Heights" },
  { province_name: "Metro Manila", city_name: "Pateros", name: "Pagasa Village" },
  { province_name: "Abra", city_name: "Bangued", name: "Pagasa Proper" },
  { province_name: "Apayao", city_name: "Kabugao", name: "Pagasa Central" },
  { province_name: "Benguet", city_name: "La Trinidad", name: "Pagasa Norte" },
  { province_name: "Ifugao", city_name: "Lagawe", name: "Pagasa Sur" },
  { province_name: "Kalinga", city_name: "Tabuk", name: "Pagasa Silangan" },
  { province_name: "Mountain Province", city_name: "Bontoc", name: "Pagasa Kanluran" },
  { province_name: "Ilocos Norte", city_name: "Laoag", name: "Pagasa Riverside" },
  { province_name: "Ilocos Norte", city_name: "Batac", name: "Pagasa Hills" },
  { province_name: "Ilocos Sur", city_name: "Vigan", name: "Sampaguita Heights" },
  { province_name: "Ilocos Sur", city_name: "Candon", name: "Sampaguita Village" },
  { province_name: "La Union", city_name: "San Fernando", name: "Sampaguita Proper" },
  { province_name: "Pangasinan", city_name: "Lingayen", name: "Sampaguita Central" },
  { province_name: "Pangasinan", city_name: "Dagupan", name: "Sampaguita Norte" },
  { province_name: "Pangasinan", city_name: "Urdaneta", name: "Sampaguita Sur" },
  { province_name: "Batanes", city_name: "Basco", name: "Sampaguita Silangan" },
  { province_name: "Cagayan", city_name: "Tuguegarao", name: "Sampaguita Kanluran" },
  { province_name: "Cagayan", city_name: "Aparri", name: "Sampaguita Riverside" },
  { province_name: "Isabela", city_name: "Ilagan", name: "Sampaguita Hills" }
]

