CITY_DATA = [
  ["Metro Manila", "Manila", false],
  ["Metro Manila", "Quezon City", false],
  ["Metro Manila", "Caloocan", false],
  ["Metro Manila", "Las Pinas", false],
  ["Metro Manila", "Makati", false],
  ["Metro Manila", "Malabon", false],
  ["Metro Manila", "Mandaluyong", false],
  ["Metro Manila", "Marikina", false],
  ["Metro Manila", "Muntinlupa", false],
  ["Metro Manila", "Navotas", false],
  ["Metro Manila", "Paranaque", false],
  ["Metro Manila", "Pasay", false],
  ["Metro Manila", "Pasig", false],
  ["Metro Manila", "San Juan", false],
  ["Metro Manila", "Taguig", false],
  ["Metro Manila", "Valenzuela", false],
  ["Metro Manila", "Pateros", true],
  ["Abra", "Bangued", true],
  ["Apayao", "Kabugao", true],
  ["Benguet", "La Trinidad", true],
  ["Ifugao", "Lagawe", true],
  ["Kalinga", "Tabuk", false],
  ["Mountain Province", "Bontoc", true],
  ["Ilocos Norte", "Laoag", false],
  ["Ilocos Norte", "Batac", false],
  ["Ilocos Sur", "Vigan", false],
  ["Ilocos Sur", "Candon", false],
  ["La Union", "San Fernando", false],
  ["Pangasinan", "Lingayen", true],
  ["Pangasinan", "Dagupan", false],
  ["Pangasinan", "Urdaneta", false],
  ["Batanes", "Basco", true],
  ["Cagayan", "Tuguegarao", false],
  ["Cagayan", "Aparri", true],
  ["Isabela", "Ilagan", false],
  ["Isabela", "Cauayan", false],
  ["Nueva Vizcaya", "Bayombong", true],
  ["Nueva Vizcaya", "Solano", true],
  ["Quirino", "Cabarroguis", true],
  ["Aurora", "Baler", true],
  ["Bataan", "Balanga", false],
  ["Bulacan", "Malolos", false],
  ["Bulacan", "Meycauayan", false],
  ["Bulacan", "San Jose del Monte", false],
  ["Nueva Ecija", "Palayan", false],
  ["Nueva Ecija", "Cabanatuan", false],
  ["Nueva Ecija", "Gapan", false],
  ["Pampanga", "San Fernando", false],
  ["Pampanga", "Angeles", false],
  ["Pampanga", "Mabalacat", false],
  ["Tarlac", "Tarlac City", false],
  ["Zambales", "Iba", true],
  ["Zambales", "Olongapo", false],
  ["Batangas", "Batangas City", false],
  ["Batangas", "Lipa", false],
  ["Batangas", "Tanauan", false],
  ["Cavite", "Trece Martires", false],
  ["Cavite", "Imus", false],
  ["Cavite", "Dasmarinas", false],
  ["Cavite", "Tagaytay", false],
  ["Laguna", "Santa Cruz", true],
  ["Laguna", "Calamba", false],
  ["Laguna", "San Pablo", false],
  ["Laguna", "Santa Rosa", false],
  ["Laguna", "Binan", false],
  ["Quezon", "Lucena", false],
  ["Quezon", "Tayabas", false],
  ["Rizal", "Antipolo", false],
  ["Marinduque", "Boac", true],
  ["Occidental Mindoro", "Mamburao", true],
  ["Occidental Mindoro", "San Jose", true],
  ["Oriental Mindoro", "Calapan", false],
  ["Palawan", "Puerto Princesa", false],
  ["Palawan", "Coron", true],
  ["Romblon", "Romblon", true],
  ["Albay", "Legazpi", false],
  ["Albay", "Ligao", false],
  ["Albay", "Tabaco", false],
  ["Camarines Norte", "Daet", true],
  ["Camarines Sur", "Pili", true],
  ["Camarines Sur", "Naga", false],
  ["Camarines Sur", "Iriga", false],
  ["Catanduanes", "Virac", true],
  ["Masbate", "Masbate City", false],
  ["Sorsogon", "Sorsogon City", false],
  ["Aklan", "Kalibo", true],
  ["Antique", "San Jose de Buenavista", true],
  ["Capiz", "Roxas City", false],
  ["Guimaras", "Jordan", true],
  ["Iloilo", "Iloilo City", false],
  ["Iloilo", "Passi", false],
  ["Negros Occidental", "Bacolod", false],
  ["Negros Occidental", "Bago", false],
  ["Negros Occidental", "Kabankalan", false],
  ["Negros Occidental", "San Carlos", false],
  ["Bohol", "Tagbilaran", false],
  ["Bohol", "Talibon", true],
  ["Cebu", "Cebu City", false],
  ["Cebu", "Danao", false],
  ["Cebu", "Toledo", false],
  ["Cebu", "Talisay", false],
  ["Cebu", "Bogo", false],
  ["Cebu", "Carcar", false],
  ["Cebu", "Naga", false],
  ["Negros Oriental", "Dumaguete", false],
  ["Negros Oriental", "Bais", false],
  ["Negros Oriental", "Bayawan", false],
  ["Negros Oriental", "Tanjay", false],
  ["Negros Oriental", "Canlaon", false],
  ["Negros Oriental", "Guihulngan", false],
  ["Siquijor", "Siquijor", true],
  ["Biliran", "Naval", true],
  ["Eastern Samar", "Borongan", false],
  ["Leyte", "Tacloban", false],
  ["Leyte", "Ormoc", false],
  ["Leyte", "Baybay", false],
  ["Northern Samar", "Catarman", true],
  ["Samar", "Catbalogan", false],
  ["Samar", "Calbayog", false],
  ["Southern Leyte", "Maasin", false],
  ["Zamboanga del Norte", "Dipolog", false],
  ["Zamboanga del Norte", "Dapitan", false],
  ["Zamboanga del Sur", "Pagadian", false],
  ["Zamboanga del Sur", "Zamboanga City", false],
  ["Zamboanga Sibugay", "Ipil", true],
  ["Bukidnon", "Malaybalay", false],
  ["Bukidnon", "Valencia", false],
  ["Camiguin", "Mambajao", true],
  ["Lanao del Norte", "Tubod", true],
  ["Lanao del Norte", "Iligan", false],
  ["Misamis Occidental", "Oroquieta", false],
  ["Misamis Occidental", "Ozamiz", false],
  ["Misamis Occidental", "Tangub", false],
  ["Misamis Oriental", "Cagayan de Oro", false],
  ["Misamis Oriental", "Gingoog", false],
  ["Misamis Oriental", "El Salvador", false],
  ["Davao de Oro", "Nabunturan", true],
  ["Davao del Norte", "Tagum", false],
  ["Davao del Norte", "Panabo", false],
  ["Davao del Norte", "Samal", false],
  ["Davao del Sur", "Digos", false],
  ["Davao del Sur", "Davao City", false],
  ["Davao Occidental", "Malita", true],
  ["Davao Oriental", "Mati", false],
  ["Cotabato", "Kidapawan", false],
  ["Sarangani", "Alabel", true],
  ["South Cotabato", "Koronadal", false],
  ["South Cotabato", "General Santos", false],
  ["Sultan Kudarat", "Isulan", true],
  ["Sultan Kudarat", "Tacurong", false],
  ["Agusan del Norte", "Butuan", false],
  ["Agusan del Norte", "Cabadbaran", false],
  ["Agusan del Sur", "Prosperidad", true],
  ["Agusan del Sur", "Bayugan", false],
  ["Dinagat Islands", "San Jose", true],
  ["Surigao del Norte", "Surigao City", false],
  ["Surigao del Sur", "Tandag", false],
  ["Surigao del Sur", "Bislig", false],
  ["Basilan", "Isabela City", false],
  ["Lanao del Sur", "Marawi", false],
  ["Maguindanao del Norte", "Datu Odin Sinsuat", true],
  ["Maguindanao del Norte", "Cotabato City", false],
  ["Maguindanao del Sur", "Buluan", true],
  ["Sulu", "Jolo", true],
  ["Tawi-Tawi", "Bongao", true]
].freeze
